server:
  port: 8080
  servlet:
    context-path: /bootcamp


spring:
  datasource:
    platform: postgres
    url: postgres://jedngnrluthodh:acd06c561b68223c02689277a70b31c35c35fb9293494bc91c38b7165170c6cd@ec2-54-197-100-79.compute-1.amazonaws.com:5432/dcemvtbb6mqp7
    username: jedngnrluthodh
    password: acd06c561b68223c02689277a70b31c35c35fb9293494bc91c38b7165170c6cd
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
    description: Projeto criado para o Bootcamp DIO - Santander

