server:
  port: 8080
  servlet:
    context-path: /bootcamp


spring:
  datasource:
    platform: postgres
    url: postgres://crkgwsvisqhsxg:485acbe907e943a1151bb31aa63df40138984c3b58e3f0a563d6832799c0c6bd@ec2-52-0-114-209.compute-1.amazonaws.com:5432/dfas19ujte7496
    username: crkgwsvisqhsxg
    password: 485acbe907e943a1151bb31aa63df40138984c3b58e3f0a563d6832799c0c6bd
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostegreSQLDialect	
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
    description: Projeto criado para o Bootcamp DIO - Santander

