server:
  port: 8080
  servlet:
    context-path: /bootcamp


spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/db_bootcamp
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

application:
    description: Projeto criado para o Bootcamp DIO - Santander

